//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankWindowsWPF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/BankWindow")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AccountBalance1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string City1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NrAccount1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NrHouse1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostCode1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AccountBalance1 {
            get {
                return this.AccountBalance1Field;
            }
            set {
                if ((this.AccountBalance1Field.Equals(value) != true)) {
                    this.AccountBalance1Field = value;
                    this.RaisePropertyChanged("AccountBalance1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City1 {
            get {
                return this.City1Field;
            }
            set {
                if ((object.ReferenceEquals(this.City1Field, value) != true)) {
                    this.City1Field = value;
                    this.RaisePropertyChanged("City1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName1 {
            get {
                return this.FirstName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.FirstName1Field, value) != true)) {
                    this.FirstName1Field = value;
                    this.RaisePropertyChanged("FirstName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName1 {
            get {
                return this.LastName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LastName1Field, value) != true)) {
                    this.LastName1Field = value;
                    this.RaisePropertyChanged("LastName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NrAccount1 {
            get {
                return this.NrAccount1Field;
            }
            set {
                if ((this.NrAccount1Field.Equals(value) != true)) {
                    this.NrAccount1Field = value;
                    this.RaisePropertyChanged("NrAccount1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NrHouse1 {
            get {
                return this.NrHouse1Field;
            }
            set {
                if ((this.NrHouse1Field.Equals(value) != true)) {
                    this.NrHouse1Field = value;
                    this.RaisePropertyChanged("NrHouse1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostCode1 {
            get {
                return this.PostCode1Field;
            }
            set {
                if ((this.PostCode1Field.Equals(value) != true)) {
                    this.PostCode1Field = value;
                    this.RaisePropertyChanged("PostCode1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street1 {
            get {
                return this.Street1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street1Field, value) != true)) {
                    this.Street1Field = value;
                    this.RaisePropertyChanged("Street1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAccount", ReplyAction="http://tempuri.org/IService1/SendAccountResponse")]
        string SendAccount(BankWindowsWPF.ServiceReference1.Account NewAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAccount", ReplyAction="http://tempuri.org/IService1/SendAccountResponse")]
        System.Threading.Tasks.Task<string> SendAccountAsync(BankWindowsWPF.ServiceReference1.Account NewAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAccount", ReplyAction="http://tempuri.org/IService1/ShowAccountResponse")]
        System.Data.DataSet ShowAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAccount", ReplyAction="http://tempuri.org/IService1/ShowAccountResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowOperation", ReplyAction="http://tempuri.org/IService1/ShowOperationResponse")]
        System.Data.DataSet ShowOperation(string NrAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowOperation", ReplyAction="http://tempuri.org/IService1/ShowOperationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowOperationAsync(string NrAccount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BankWindowsWPF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BankWindowsWPF.ServiceReference1.IService1>, BankWindowsWPF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendAccount(BankWindowsWPF.ServiceReference1.Account NewAccount) {
            return base.Channel.SendAccount(NewAccount);
        }
        
        public System.Threading.Tasks.Task<string> SendAccountAsync(BankWindowsWPF.ServiceReference1.Account NewAccount) {
            return base.Channel.SendAccountAsync(NewAccount);
        }
        
        public System.Data.DataSet ShowAccount() {
            return base.Channel.ShowAccount();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowAccountAsync() {
            return base.Channel.ShowAccountAsync();
        }
        
        public System.Data.DataSet ShowOperation(string NrAccount) {
            return base.Channel.ShowOperation(NrAccount);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowOperationAsync(string NrAccount) {
            return base.Channel.ShowOperationAsync(NrAccount);
        }
    }
}
