//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankWindowsWPF.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAccount", ReplyAction="http://tempuri.org/IService1/SendAccountResponse")]
        string SendAccount(BankWindow.Account NewAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAccount", ReplyAction="http://tempuri.org/IService1/SendAccountResponse")]
        System.Threading.Tasks.Task<string> SendAccountAsync(BankWindow.Account NewAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAccount", ReplyAction="http://tempuri.org/IService1/ShowAccountResponse")]
        System.Data.DataSet ShowAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAccount", ReplyAction="http://tempuri.org/IService1/ShowAccountResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowOperation", ReplyAction="http://tempuri.org/IService1/ShowOperationResponse")]
        System.Data.DataSet ShowOperation(string NrAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowOperation", ReplyAction="http://tempuri.org/IService1/ShowOperationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowOperationAsync(string NrAccount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BankWindowsWPF.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BankWindowsWPF.ServiceReference2.IService1>, BankWindowsWPF.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendAccount(BankWindow.Account NewAccount) {
            return base.Channel.SendAccount(NewAccount);
        }
        
        public System.Threading.Tasks.Task<string> SendAccountAsync(BankWindow.Account NewAccount) {
            return base.Channel.SendAccountAsync(NewAccount);
        }
        
        public System.Data.DataSet ShowAccount() {
            return base.Channel.ShowAccount();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowAccountAsync() {
            return base.Channel.ShowAccountAsync();
        }
        
        public System.Data.DataSet ShowOperation(string NrAccount) {
            return base.Channel.ShowOperation(NrAccount);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowOperationAsync(string NrAccount) {
            return base.Channel.ShowOperationAsync(NrAccount);
        }
    }
}
